### ISSUE TITLE
question on duplicate corner case, edge.ripley

### ISSUE THREAD

**Issue by Marjolein9** [spatstat/spatstat.core#13]
This may not be an issue, but wanted to check.

For edge ripley, if you have a duplicated value for i and j in a corner, the corner == True should add pi/2 to the "ext" value to compensate for the corner. However, even though i is in the corner, since the distance between i and j is 0, the corner is not really cutting anything off. So should the result in that case be more like how duplicate value elsewhere are treated and return 1 as the weight?

library(spatstat)
#created dataframe  with mark in corner (0, 0)
y <- c(0, 1)
x <- c(0, 1)
mark <- c("yes", "yes")
df <- data.frame("x" = x, "y" = y, "mark" = mark)
df$mark <- as.factor(df$mark)
W <- owin( c(0, 5), c(0, 5))
all_pp <- as.ppp( df, W = W)
#using interpreted for debugged
edge.Ripley(all_pp, c(0, 0), method = c("interpreted"))
returns (with the corner case problem of the last version corrected):
         [,1]
[1,] 1.333333
[2,] 1.000000

**Comment by rolfTurner** [comment]
I may, as so often happens, be misunderstanding something here, but spatstat is designed to deal (only) with "orderly" point processes.  It is assumed that multiple occurrences of events at the same spatial location cannot occur.  Hence interpoint distances of 0 are not/should not be allowed.

If you really want to deal with point patterns that have multiple events at the same location, then different software and different theory is required.  I don't know of any software  or methodology for dealing with such patterns, but there may be some out there somewhere.

The "corner correction" is inappropriate for 0-valued interpoint distances,
but the crucial issue is that  0-valued interpoint distances are inappropriate.

**Comment by Marjolein9** [comment]
You have understood what I was asking, and your answer makes sense :) Thanks for explaining this to me!

**Comment by baddstats** [comment]
This is not correct. 

It is true that the vast majority of existing statistical methods for spatial point patterns are based on theory which assumes that the point process is **simple** (i.e. that coincident points are impossible) [note: _"orderly"_ point processes are a stronger assumption which is not always assumed]

However, coincident points do occur frequently in real data, as discussed in section 3.4.4 of [the spatstat book](https://book.spatstat.org). Accordingly, the code in `spatstat` is designed to handle coincident points correctly, whenever it is clear what the "correct" behaviour should be. 

The functions `Kest`, `pcf.ppp` and their relatives are designed to handle coincident points. 

The case you mention is a bug since the correct value of `edge.Ripley` for coincident points is 1. I will fix this bug.
